# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: update

on:
  workflow_dispatch:
  schedule:
    - cron: '59 0 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - uses: Swatinem/rust-cache@v1

    - run: |
        cargo build
        ./target/debug/public-stun
        git config --global user.name 'gcxfd'
        git config --global user.email 'i@rmw.link'
        git add -u
        git commit -m'update'
        git push
